### ISSUE TITLE
Task create project

### ISSUE THREAD

**Issue by Group2VietTriDao** [Group2VietTriDao/MockProject_072024_Group2#1]

**Comment by HuXu689** [comment]
Link gg drive: https://drive.google.com/drive/folders/1zR1p3vldJ7UwbnsTmlkF4WrFTRrg0MpW?usp=sharing
Link github: https://github.com/users/Group2VietTriDao/projects/1
Link group 2 profile: https://docs.google.com/spreadsheets/d/1LKNGmVPPoAHz3nqXyWSm-bnO-l-g83nKc7JULkh2slE/edit?usp=sharing
Link gg meet: https://meet.google.com/xwz-fqbg-wwe
