### ISSUE TITLE
Research software business 

### ISSUE THREAD

**Issue by BaoHuynh12** [Group2VietTriDao/MockProject_072024_Group2#12]
[https://mail.google.com/mail/u/0?ui=2&ik=e28124e547&attid=0.1&permmsgid=msg-f:1805553941763161699&th=190e9dbe69997e63&view=att&disp=safe&realattid=f_lz18yq0v0](url)

**Comment by leduykhang2k** [comment]
Done Task

**Comment by leduykhang2k** [comment]
![FlowchartDiagram_SG](https://github.com/user-attachments/assets/938c9044-9daa-4c84-8cdf-29a1e93a5a32)
