### ISSUE TITLE
Task learn the GitHub workflow and push code

### ISSUE THREAD

**Issue by Group2VietTriDao** [Group2VietTriDao/MockProject_072024_Group2#15]
Objective: DEV GitHub Training
Task: 
1. Each developer will push their code to GitHub.
2. Developers will then practice merging their code.
3. Follow the instructions in the document: [MockProject_Huong dan su dung GITHUB.docx].
Completion Comment: Comment "Task completed" when the task is done.
[MockProject_Huong dan su dung GITHUB.docx](https://github.com/user-attachments/files/16405944/MockProject_Huong.dan.su.dung.GITHUB.docx)

**Comment by HuXu689** [comment]
Task completed

**Comment by huynhductruong** [comment]
Finished


![Image](https://github.com/user-attachments/assets/30f2ce88-86eb-4a83-bc7c-c9406c4111ce)

**Comment by HoangAnhTuan2902** [comment]
done! 


![Image](https://github.com/user-attachments/assets/d25a385c-ab19-4b4e-b45f-f351227a8c41)

**Comment by HuongPhanViet** [comment]
![Image](https://github.com/user-attachments/assets/38097fd0-f562-47a6-b594-13948babeec7)

Finish

**Comment by Lemaner** [comment]
Finished

**Comment by ninhtvo** [comment]
![Image](https://github.com/user-attachments/assets/6b066774-37a2-492c-a755-8479687941bd)

Finish
