### ISSUE TITLE
Task learn to log and manage bugs on GitHub

### ISSUE THREAD

**Issue by Group2VietTriDao** [Group2VietTriDao/MockProject_072024_Group2#16]
Objective: TESTER GitHub Training
Task:
1. Study the following two guides to learn the bug logging process:
- Link log bug guide: https://docs.google.com/document/d/e/2PACX-1vQKwGmhvN9z7nuiS_Nh5ukmEFLHhlUe74d9p4-EL8vBKsNjCE0uiaUlZp--AdJuje7Eu0eO-g5QBgEv/pub
- Link log bug with GitHub guide: https://docs.google.com/document/d/e/2PACX-1vQ5ILaOATxEAAAhHOc
2. Reference the file [MockProject_Defect List Sample.xlsx] as needed
[MockProject_Defect List Sample.xlsx](https://github.com/user-attachments/files/16406012/MockProject_Defect.List.Sample.xlsx)
gjeI9sJOfjexdI_KVPkJEx_DAPQ4K2ni_cibboBWIIx1UzxqNwqH-d9_6aZCr/pub

Completion Comment: Comment "Task completed" when the task is done.

**Comment by hoangthuy99** [comment]
Task completed


![Image](https://github.com/user-attachments/assets/8794f6f6-5a1e-4a71-b199-5594c4376c7d)

https://github.com/hoangthuy99/exercise1/issues/1
