### ISSUE TITLE
Task Learn Figma Design Skills

### ISSUE THREAD

**Issue by Group2VietTriDao** [Group2VietTriDao/MockProject_072024_Group2#2]
Objective: FRONTEND, TESTER, BA Improve Figma design skills.
Tasks:
- Search and follow Figma tutorial videos on YouTube.
- Share useful resources and tutorials within the team.

**Comment by huynhductruong** [comment]
Finished

**Comment by HoangAnhTuan2902** [comment]
Finished

**Comment by Lemaner** [comment]
Finished

**Comment by BaoHuynh12** [comment]
Finished

**Comment by bichquyen05** [comment]
Finished.
Link youtube: https://youtu.be/FTFaQWZBqQ8?si=8XLBs2lAamFbhGwB
