### ISSUE TITLE
Task design figma for Staff

### ISSUE THREAD

**Issue by Group2VietTriDao** [Group2VietTriDao/MockProject_072024_Group2#26]
Requirements:

1. Members should visit [Google Spreadsheet] to receive their tasks. Each member is required to complete 2 tasks by the end of today
https://docs.google.com/spreadsheets/d/1LKNGmVPPoAHz3nqXyWSm-bnO-l-g83nKc7JULkh2slE/edit?gid=132755721#gid=132755721
2. Detailed requirements for each page can be found: https://docs.google.com/document/d/1-L5ggdpQVD8zguyOFXet66IwJuD7MNSAW3OnqinCzQA/edit)
3. Once a task is completed, members should comment "finish".

BACKEND, BA:
1. Login Page
2. Security Company Home Page
3. Customer Management
4. Customer Information
5. Edit Customer Information
6. Security Guard Management
7. Security Guard Information
8. Edit Security Guard Information
9. Manage Service Requests
10. Manage Contracts
11. Assign Security Guards
12. Attendance Management
13. Customer Feedback Management
14. Training Management
15. Reports and Statistics

**Comment by TuanStark** [comment]
Security Guard Management

**Comment by Lemaner** [comment]
Customer Information

**Comment by HuXu689** [comment]
Done Manage Service Requests, Manage Contracts

![Image](https://github.com/user-attachments/assets/9f25363c-7b8c-4200-9bdb-2f47bf1e49cc)

**Comment by Lemaner** [comment]
![Image](https://github.com/user-attachments/assets/1063a054-5a93-48bd-a0f9-c7328fa9400b)



![Image](https://github.com/user-attachments/assets/9c5c91f7-f46f-475e-be13-9a2cedb0d60f)



![Image](https://github.com/user-attachments/assets/dfc92ec1-0990-4e7c-abff-1c87bafc8bc5)



![Image](https://github.com/user-attachments/assets/5db19a8f-28a3-42f3-99d3-785e24fb624d)


![Image](https://github.com/user-attachments/assets/b92cf8dd-7f1e-4ec4-802c-306b1eb8c460)



Finished Customer Feedback Management and Training Management
