### ISSUE TITLE
Task design figma for Security Guard

### ISSUE THREAD

**Issue by Group2VietTriDao** [Group2VietTriDao/MockProject_072024_Group2#27]
Requirements:

1. Members should visit [Google Spreadsheet] to receive their tasks. Each member is required to complete 2 tasks by the end of today
https://docs.google.com/spreadsheets/d/1LKNGmVPPoAHz3nqXyWSm-bnO-l-g83nKc7JULkh2slE/edit?gid=132755721#gid=132755721
2. Detailed requirements for each page can be found: https://docs.google.com/document/d/1-L5ggdpQVD8zguyOFXet66IwJuD7MNSAW3OnqinCzQA/edit)
3. Once a task is completed, members should comment "finish".

FRONTEND:
1. Login Page
2. Security Guard Home Page
3. Work Schedule
4. Clock In/Out
5. Training
6. Work Reports
7. Update Profile
8. Security Guard Information

**Comment by seaesa** [comment]
Completed Login Page.

**Comment by HuongPhanViet** [comment]
![Image](https://github.com/user-attachments/assets/88f0ea9f-2a6a-4f44-8be3-85e73e332d5d)

Finish

**Comment by ninhtvo** [comment]
![Image](https://github.com/user-attachments/assets/b53e5edf-36a6-475d-8e1a-d318fe12901d)

Finish
