### ISSUE TITLE
Task FRONTEND Team to learn about responsive design

### ISSUE THREAD

**Issue by Group2VietTriDao** [Group2VietTriDao/MockProject_072024_Group2#28]
Requirements:
1. Refer to the following link to learn about responsive design: [Responsive Tutorial](https://hocwebchuan.com/tutorial/responsive/)
Note: From now on, when designing screens, all DEV must apply responsive design to all screens they are responsible for.
2. Code the Manage Service Requests interface as designed in Figma, the Staff section. Apply the responsive design learned to the interface: [Figma Design](https://www.figma.com/design/qh9DvigMzsle4qTS9a8Sgl/Figma-basics?node-id=723-656&t=TRUgMEp3UkYf2urI-1)
3. After completion, each member should take a screenshot of the coded interface. Required screenshots: 1 laptop interface, 1 mobile interface.

**Comment by HuongPhanViet** [comment]
Finish

![Image](https://github.com/user-attachments/assets/9ce6710f-08fb-4cd6-9f1f-09ae8b5337df)



![Image](https://github.com/user-attachments/assets/12e6e74d-a4f4-4642-8ee3-d5e065db08c6)



![Image](https://github.com/user-attachments/assets/85fdc157-8667-4451-bfe4-a0c4c3d1608a)



![Image](https://github.com/user-attachments/assets/02ec9ba4-8735-45e9-9999-22816286df36)

**Comment by seaesa** [comment]
Done!


![Image](https://github.com/user-attachments/assets/51c10bdd-c022-41d0-b969-e1fb6da22272)



![Image](https://github.com/user-attachments/assets/e10140d4-cf65-47e0-a074-2708ef06e8b4)
