### ISSUE TITLE
Task BA + Tester to learn how to test Responsive Web Design

### ISSUE THREAD

**Issue by Group2VietTriDao** [Group2VietTriDao/MockProject_072024_Group2#29]
Requirements:
1. Refer to the following links:
> [Difference Between Adaptive and Responsive Design](https://idesign.vn/graphic-design/su-khac-nhau-giua-thiet-ke-web-adaptive-va-responsive-438967.html)
> [Difference Between Adaptive and Responsive Design (Alternative)](https://bizmac.com/blog/tin-cong-nghe/su-khac-biet-giua-adaptive-design-va-responsive-design.html)
> [How
 to Test Responsive Web Design](https://viblo.asia/p/test-responsive-web-design-nhu-the-nao-OeVKBgkMZkW)
2. Practice finding errors when testing the responsive web design for the following website: [GDT Website](https://www.gdt.gov.vn/wps/portal)
> Note: Use the Chrome browser to test, with the help of DevTools by pressing F12 in Chrome. Refer to the following link to learn how to use DevTools: [DevTools Guide](https://viblo.asia/p/test-responsive-va-device-specific-viewports-tren-devtools-f12-cua-browser-phan-1-XL6lAvgB5ek)
3. After completing the task, comment "finish" and provide the file with the list of errors found during testing.
Note: From now on, when performing tests, all testers must test the responsiveness of all screens they are responsible for.

**Comment by bichquyen05** [comment]
finish
[DaoThiBichQuyen_TestResponsive.xlsx](https://github.com/user-attachments/files/16439038/DaoThiBichQuyen_TestResponsive.xlsx)

**Comment by BaoHuynh12** [comment]
[TRes_HuynhBaBao.xlsx](https://github.com/user-attachments/files/16444208/TRes_HuynhBaBao.xlsx)
