### ISSUE TITLE
Task Review SQL Skills

### ISSUE THREAD

**Issue by Group2VietTriDao** [Group2VietTriDao/MockProject_072024_Group2#3]
Objective: BA, TESTER Refresh and practice SQL skills.
Tasks:
- Study the [SQLCoBan_DB_NghiepVu_1.xlsx] file.
- Complete exercises in the [SQLCoBan_ThucHanhSQL_DB1_PhanCoBan.docx] file up to question 17 (excluding question 16).
- Perform the exercises directly on SQL Server.
- Decide on a common SQL Server version (recommend using SQL Server 2014 for its lightweight features).

[SQLCoBan_DB_NghiepVu_1.xlsx](https://github.com/user-attachments/files/16368351/SQLCoBan_DB_NghiepVu_1.xlsx)
[SQLCoBan_ThucHanhSQL_DB1_PhanCoBan.docx](https://github.com/user-attachments/files/16368366/SQLCoBan_ThucHanhSQL_DB1_PhanCoBan.docx)

**Comment by leduykhang2k** [comment]
[DataSQL.zip](https://github.com/user-attachments/files/16373129/DataSQL.zip)

**Comment by BaoHuynh12** [comment]
[HuynhBaBao.zip](https://github.com/user-attachments/files/16378487/HuynhBaBao.zip)

**Comment by bichquyen05** [comment]
[DaoThiBichQuyen.zip](https://github.com/user-attachments/files/16380805/DaoThiBichQuyen.zip)
