### ISSUE TITLE
Task BACKEND Team to design database

### ISSUE THREAD

**Issue by Group2VietTriDao** [Group2VietTriDao/MockProject_072024_Group2#30]
Requirements:
1. Refer to the project requirements: [Project Requirements](https://drive.google.com/drive/folders/1R00PcdTZd3v6FzJ1I06bjbp8lIwqgC4b)
2. Each member should design a detailed database for the system.
3. After completing the task, comment "finish" and provide the file or link to the designed database.

**Comment by thaingocquy07082003** [comment]
finish

![Image](https://github.com/user-attachments/assets/e2114278-480c-4c71-9502-5e3bc91ae211)

link : https://drive.google.com/file/d/1_U4QTbdw153Sb8jTzuba5k7sWhRsxZ1d/view?usp=sharing

**Comment by Lemaner** [comment]
https://drive.google.com/file/d/1gsFg6m57upmU0DsCaM5JfUYYOVVpyhI_/view?usp=drive_link
Finished

**Comment by hoangthuy99** [comment]
Finished


![Image](https://github.com/user-attachments/assets/e7b7bd37-e7f1-433b-b882-8259bfe6d5c7)
