### ISSUE TITLE
Task redesign figma interfaces - phase 2

### ISSUE THREAD

**Issue by HuXu689** [Group2VietTriDao/MockProject_072024_Group2#31]
Requirements:
Redesign the following Figma interfaces:
Customer
1. Login, Register, Forgot Password Page
2. Customer Home Page
3. New Service Request
4. Manage Service Requests
5. Manage Contracts
6. Submit Feedback
7. Customer Information
8. Edit Customer Information

Security Company (Staff)
1. Login Page
2. Security Company Home Page
3. Customer Management
4. Security Guard Management
5. Manage Service Requests
6. Manage Contracts
7. Assign Security Guards
8. Attendance Management
10. Customer Feedback Management
11. Training Management
12. Reports and Statistics

Security Guard
1. Login Page
2. Security Guard Home Page
3. Work Schedule
4. Clock In/Out
5. Training
6. Work Reports
7. Update Profile
8. Security Guard Information
9. Note: Ensure that all redesigned interfaces are responsive.

**Comment by TuanStark** [comment]
New Service Request
Manage Contracts
Submit Feedback
Customer Information

**Comment by TuanStark** [comment]
![Image](https://github.com/user-attachments/assets/8eac0a8d-86e9-48ef-a1ff-a73807a7733c)

**Comment by TuanStark** [comment]
CUSTOMER - NewService Request

![Image](https://github.com/user-attachments/assets/075982a4-702a-46cd-934e-0e0ed950ffce)

**Comment by TuanStark** [comment]
STAFF - ManageContracts

![Image](https://github.com/user-attachments/assets/c7f75fc1-d5a7-4469-b1bc-9d93e5ad8097)

**Comment by TuanStark** [comment]
CUSTOMER - submit feedback

![Image](https://github.com/user-attachments/assets/5d1bca9a-ab29-4daf-a81a-198860c262b3)
