### ISSUE TITLE
Task database design for the system - phase 2

### ISSUE THREAD

**Issue by Group2VietTriDao** [Group2VietTriDao/MockProject_072024_Group2#32]
Assigned to: All team members,
Deadline: Complete by 5:00 PM today
Task Requirements:
1. Complete the detailed database design:
> Based on the basic database design, finish detailing the database by listing additional necessary columns for each table.
![ERDBodyGuard](https://github.com/user-attachments/assets/f9445fbe-8e14-4ec4-ad6f-dd9c036e9394)
2. List the fixed components of the system:
> Define system statuses, e.g., 'Completed', 'Pending Approval', etc.
> Define service types, e.g., 'Personal Security', 'Event Security', etc.
> Define roles, e.g., 'User', 'Guard', etc.
Note: Some tables may require specific columns such as 'Created By', 'Created Date', etc.
3. Reporting Requirements:
> Upon completing the task, each member should comment with a screenshot, file, or link to their own design.

**Comment by Group2VietTriDao** [comment]
Basic database design: 
https://drive.google.com/file/d/1cNv4K6Wyga3L58qOnv23KU2r3zY9i7e3/view?usp=drive_link

**Comment by TuanStark** [comment]
NHỮNG CÁI EM KHOANH ĐỎ LÀ EM TỰ THÊM VÀO, NẾU KHÔNG HỢP LÍ THÌ MÌNH CÓ THỂ XÓA

![Image](https://github.com/user-attachments/assets/c49f6b89-ab7b-48ba-8b13-8d25a6591f9f)



![Image](https://github.com/user-attachments/assets/785ffd70-6589-4361-baab-1f738274c1c1)

**Comment by khungking909** [comment]
Finished

![Image](https://github.com/user-attachments/assets/375d17b8-91b1-4697-a6c6-2ae6879bb807)

**Comment by BaoHuynh12** [comment]
cái của tui nó hơi khác một tí ông xem ik nha 


![Image](https://github.com/user-attachments/assets/9d6ab394-b8a4-4016-a682-b19e4e26eaa4)

**Comment by ninhtvo** [comment]
Finished, tui chỉ biết sơ sơ thôi nên không có bt đúng không mọi người thông cảm.

![Image](https://github.com/user-attachments/assets/806606a6-08f0-4d5a-86df-13d504b07cb3)

**Comment by Lemaner** [comment]
![Image](https://github.com/user-attachments/assets/13b9c64b-1b52-4cff-9069-05bd8fe25d60)

https://drive.google.com/file/d/1envlO8sS146SriPaw0Ieuas8Inlvawt_/view?usp=drive_link

Nay ko có thời gian làm nhiều nên làm sơ sơ thôi. Finished

**Comment by HuXu689** [comment]
Nay có xíu việc, tối mới rảnh làm xíu. Mng thông cảm nha ^^

![Image](https://github.com/user-attachments/assets/31c65801-bd72-4d3a-b1cf-7984b6111d2e)

**Comment by HuXu689** [comment]
https://drive.google.com/drive/folders/1TG__ERlOyriXa4ynFThhpsMks3ZVT7P2
