### ISSUE TITLE
Task create sample data for database

### ISSUE THREAD

**Issue by Group2VietTriDao** [Group2VietTriDao/MockProject_072024_Group2#33]
Assignees: All Members
Task:
1. Review the existing database structure and add sample data: https://drive.google.com/drive/folders/1TG__ERlOyriXa4ynFThhpsMks3ZVT7P2
> Each member should review the current database structure.
> Add at least 5 sample records to each table in the database.
2. Use INSERT INTO statements in SQL Server to add data:
> Use SQL INSERT INTO statements to populate the tables with sample data.
> Ensure that the data complies with the database constraints and rules.
3. Submit the code via a link or file:
> After completing the task, upload the SQL code or share the link to the file or attach the file with the code in this issue.

**Comment by HuXu689** [comment]
Finish

[insertData.txt](https://github.com/user-attachments/files/16469831/insertData.txt)

**Comment by TuanStark** [comment]
DATATEST

[TẠO TABLE VÀ THÊM DỮ LIỆU TEST VÀO DATABASE.docx](https://github.com/user-attachments/files/16486519/T.O.TABLE.VA.THEM.D.LI.U.TEST.VAO.DATABASE.docx)

**Comment by Lemaner** [comment]
Finished


[SampleData.txt](https://github.com/user-attachments/files/16488662/SampleData.txt)
