### ISSUE TITLE
Task Discuss and Unified Framework

### ISSUE THREAD

**Issue by Group2VietTriDao** [Group2VietTriDao/MockProject_072024_Group2#4]
Objective: BACKEND, FRONTEND Agree on the framework and libraries to be used for the project.
Tasks:
- Select a framework and libraries that multiple team members are familiar with.
- Decide on the versions of the framework and libraries.
- Define naming conventions for the project, packages, classes, variables, and methods.
- Establish commenting standards (comments must be in English).
- Create a Coding Convention file similar to [Java Coding Convention.xls].
- Set rules for using common classes for constants (e.g., database server paths, usernames, passwords).
- Agree on the IDE and specific version to use.

[Java Coding Convention.xls](https://github.com/user-attachments/files/16368387/Java.Coding.Convention.xls)

**Comment by HuXu689** [comment]
I. Sql Server SQL2022-SSEI-Dev
II. REACJS
- 	ReactJs + Typescript vs Vite tool genarate
- 	ReactJS combined with Tailwind
- 	Framework: ReactJS
- 	IDE: Visual Studio Code
III. JAVA
- 	Framework: Java Spring Boot Security 6.0
- 	Language: Java JDK 17
- 	IDE: Visual Studio Code
IV. PHP
- 	Framework: Laravel 11.13.0
- 	Language: PHP 8.2.12
- 	IDE: Visual Studio Code
V. PYTHON
- 	Framework: Django 5.0
- 	Language: Python 3.12
- 	IDE: Visual Studio Code
VI. NODEJS
- 	Framework: Express 4.19.2
- 	IDE: Visual Studio Code
