### ISSUE TITLE
Task BACKEND code review

### ISSUE THREAD

**Issue by Group2VietTriDao** [Group2VietTriDao/MockProject_072024_Group2#40]
Title: Review backend source code
Description:
Assigned Group: BACKEND
Each member makes a word review file and uploads it to Google Drive, comment in GITHUB
Review Content:
> 1. Is the code easy to read and understand?
> 2. Are the naming conventions for variables, functions, classes, etc., consistent with the Coding Convention file agreed upon by the team?
> 3. Is the code properly formatted and organized?
> 4. Are comments used to explain the code?
> 5. Are variable names, function names, and comments written in English?
> 6. Is the code logic clear and accurate?
> 7. Does the code handle try-catch exceptions appropriately?
> 8. Is the code efficient and optimized? Does it require any improvements?
> 9. Are appropriate algorithms and data structures used?
> 10. Are files and database connections opened and closed correctly in the code?
> 11. Is the code easy to maintain and debug?
> 12. Is the code modularized appropriately? Are there any methods longer than 100 lines?
> 13. Does the code use the tools and frameworks that were agreed upon at the beginning of the project?
> 14. Are there more than three nested if statements in the code? (This is highly discouraged.)
> 15. Are there any SQL queries using select *? (Specific columns should be selected instead.)
> Outcome: Capture evidence with screenshots and save it in a result file to send to the Mentor.

**Comment by Lemaner** [comment]
[Review code API python.docx](https://github.com/user-attachments/files/16621574/Review.code.API.python.docx)
[Review code Python.docx](https://github.com/user-attachments/files/16621575/Review.code.Python.docx)
