### ISSUE TITLE
Task FRONTEND code review (ReactJS)

### ISSUE THREAD

**Issue by Group2VietTriDao** [Group2VietTriDao/MockProject_072024_Group2#41]
Title: Review frontend ReactJS source code
Description:
Assigned Group: FRONTEND ReactJS
Each member makes a word review file and uploads it to Google Drive, comment in GITHUB
Review Content:
> 1. Is the code easy to read and understand?
> 2. Are the naming conventions for components, props, states, etc., consistent and in English?
> 3. Is the code properly formatted and organized?
> 4. Are comments used to explain the code? Are the comments written in English?
> 5. Is the code logic clear and accurate?
> 6. Does the code handle exceptions (errors) properly?
> 7. Is the code easy to maintain and debug?
> 8. Are the libraries and frameworks used as agreed upon with the project team?
> 9. Is the user interface divided into small, independent, and reusable components?
> 10. Are props used to pass data between components?
> 11. Is the state used to store the internal data of components?
> 12. Are ReactJS hooks properly used to manage state, lifecycle, and side effects?
> 13. Are common hooks like useState, useEffect, useRef, and useContext used correctly?
> 14. Are Higher-Order Components (HOCs) used to share logic between components?
> 15. Are HOCs used to avoid duplicate code?
> 16. Is Redux or useReducer used to manage the global state of the application?
> Outcome: Capture evidence with screenshots and save it in a result file to send to the Mentor.

**Comment by seaesa** [comment]
file review source code huong phan
https://docs.google.com/document/d/1T-6wkdHLotaOMbsetdOmGcScrSzlp2BMUD8Ddxxv5GI/edit?usp=sharing

**Comment by HuongPhanViet** [comment]
review source code Dang Ngoc Hai
https://drive.google.com/drive/folders/1qIKR3-d9BGQgNLNW-_FNlvACVWklLvvc?usp=drive_link
