### ISSUE TITLE
Task Install Sql Server For BA, Backend, Tester

### ISSUE THREAD

**Issue by Group2VietTriDao** [Group2VietTriDao/MockProject_072024_Group2#5]
Sql Server SQL2022-SSEI-Dev: https://www.microsoft.com/en-us/sql-server/sql-server-downloads?msockid=19911c071e9e6d06199008931fcc6cff
Mac: https://www.youtube.com/watch?v=9c7Ti2OcLZg
- Take a screenshot of the settings and put them in the comments

**Comment by huynhductruong** [comment]
finish


![Image](https://github.com/user-attachments/assets/46b74ad6-d6d1-459e-847d-5ea9f47f8c84)

**Comment by HuXu689** [comment]
Finish task


![Image](https://github.com/user-attachments/assets/fd7b9889-cf78-4431-a0a0-090a168c54cd)

**Comment by HoangAnhTuan2902** [comment]
![Screenshot 2024-07-25 154135](https://github.com/user-attachments/assets/92de0cd9-f815-4e9c-9def-526992429ab1)
finish

**Comment by HuongPhanViet** [comment]
![Image](https://github.com/user-attachments/assets/9930c4ba-0fc7-41ef-816f-198f1c0ea4f9)

Finish

**Comment by hoangthuy99** [comment]
Finish

![Image](https://github.com/user-attachments/assets/f8870fc5-ffd9-4091-aea4-ee105baef2cf)

**Comment by Lemaner** [comment]
![Untitled](https://github.com/user-attachments/assets/765171a4-a1b3-4203-8b15-3fc8f1c6afbc)
finish

**Comment by badwolf2** [comment]
Finish



![Image](https://github.com/user-attachments/assets/af136d3f-6b7b-423a-968c-076ebac3ad8d)

**Comment by ninhtvo** [comment]
Finish
![download](https://github.com/user-attachments/assets/634ad8a2-408b-4ce4-a68d-deefe98f8d4f)

**Comment by BaoHuynh12** [comment]
Finished

![Image](https://github.com/user-attachments/assets/93cc0ab9-754b-48e5-8a4d-883165298938)
