### ISSUE TITLE
Task select a template for web interface

### ISSUE THREAD

**Issue by Group2VietTriDao** [Group2VietTriDao/MockProject_072024_Group2#6]
Objective: DEV + TESTER + BA select a template for web interface
Task:
- Choose a theme for our website with the business case of "Security Guard Rental Management Website in the USA."
- Upload the chosen template to Google Drive and add a comment in this issue with the link to the template.

**Comment by HuXu689** [comment]
Template: https://xpressguards.com/personal-security-guards/
