### ISSUE TITLE
Task code the login functionality

### ISSUE THREAD

**Issue by Group2VietTriDao** [Group2VietTriDao/MockProject_072024_Group2#7]
Objective: BACKEND code the login functionality
Task:
- Code the backend functionality for the login screen according to the agreed framework.
- Take a screenshot of the code for the login functionality and upload it to Google Drive.
- Add a comment in this issue with the link to the screenshot.

**Comment by thaingocquy07082003** [comment]
Finish

![Image](https://github.com/user-attachments/assets/1101ed29-6d32-497f-9c03-1e9aa66bc13a)

**Comment by huynhductruong** [comment]
![Image](https://github.com/user-attachments/assets/d196a657-3e5d-4860-8293-5f965dd7c55d)

Finished

**Comment by Lemaner** [comment]
![Image](https://github.com/user-attachments/assets/67376bdf-7662-4992-a705-b4e8219fbedc)

finished

**Comment by hoangthuy99** [comment]
Finish

![Image](https://github.com/user-attachments/assets/11a31e80-f6d9-4763-986b-3a7cefcce07c)

**Comment by hoangthuy99** [comment]
Finish


![Image](https://github.com/user-attachments/assets/41e249df-5983-4442-85de-dc521593ccfb)

**Comment by HuXu689** [comment]
Finish task

![Image](https://github.com/user-attachments/assets/0205b50c-5423-4974-9021-d436eafdc854)

**Comment by badwolf2** [comment]
finished
![image](https://github.com/user-attachments/assets/bb545fa9-7a67-4563-a38e-f89cbb002358)

**Comment by LT-Vuong-86** [comment]
![Image](https://github.com/user-attachments/assets/11fe8cf4-0626-4743-95ea-9e5f6dac0512)

**Comment by HuongPhanViet** [comment]
Finish


![Image](https://github.com/user-attachments/assets/877014bf-f773-4466-a5fd-f9c18eb27a1b)
