### ISSUE TITLE
Task code the login screen interface

### ISSUE THREAD

**Issue by Group2VietTriDao** [Group2VietTriDao/MockProject_072024_Group2#8]
Objective: FRONTEND code the login screen interface
Task:
- Code the frontend interface for the login screen according to the agreed framework.
- Take a screenshot of both the code and the login interface and upload them to Google Drive.
- Add a comment in this issue with the links to the screenshots.

**Comment by huynhductruong** [comment]
![Image](https://github.com/user-attachments/assets/17e0052a-dda5-4f34-91ad-d58fe8de9cd2)



![Image](https://github.com/user-attachments/assets/8e312260-57f7-4d68-a438-cd70a720eb5c)

Finished

**Comment by seaesa** [comment]
![login screen](https://github.com/user-attachments/assets/dc33a170-f9e6-4c72-b4c2-6b654818a9e3)
Done!

**Comment by ninhtvo** [comment]
Finish


![Image](https://github.com/user-attachments/assets/ca81b23a-be93-48d1-ab1f-b94ca0044280)

**Comment by HuongPhanViet** [comment]
![Image](https://github.com/user-attachments/assets/3186fbe7-d60e-4df1-8d1e-f52bc2124351)





Finish

**Comment by HoangAnhTuan2902** [comment]
done

![Image](https://github.com/user-attachments/assets/bf810ecd-9f7b-4494-9834-557ee46a18eb)



![Image](https://github.com/user-attachments/assets/51bf06d7-9ab9-4e5a-929a-0bdfab5890c7)
