### ISSUE TITLE
Task research and write test cases

### ISSUE THREAD

**Issue by Group2VietTriDao** [Group2VietTriDao/MockProject_072024_Group2#9]
Objective: TESTER research and write test cases
Task:
- Research and write test cases using the template provided by the mentor.
- Reference file: [MockProject_Test Case_Sample.xlsx]
- Note: Each real project will have a different template, and testers must use the template provided by the specific project.
- For this project, testers must write test cases according to the provided template, not any other template.
- Upload the written test cases to Google Drive.
- Add a comment in this issue with the link to the uploaded test cases.

**Comment by BaoHuynh12** [comment]
Finished

[TC_HuynhBaBao.xlsx](https://github.com/user-attachments/files/16387698/TC_HuynhBaBao.xlsx)

**Comment by bichquyen05** [comment]
Finished
[TCLogin_DaoThiBichQuyen.xlsx](https://github.com/user-attachments/files/16393709/TCLogin_DaoThiBichQuyen.xlsx)
